name: Docker workflow

on:
  push:
    branches: [action]

jobs:
  build:
    runs-on: ubuntu-latest
    uses: actions/checkout@v4
    steps:
    - name: build-bin
      run:  g++ -o main main.cpp
    - name: login
      uses: docker/login-action@v3
      with:
        usaername:  ${{ secrets.DOCKER_USERNAME }}
        password:   ${{ secrets.DOCKER_PASSWORD }}
    - name: setup-buildx
      uses: docker/setup-buildx-action@v3
    - name: build-and-push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/test-img:latest
          ${{ secrets.DOCKER_USERNAME }}/test-img:${{ github.sha }}
